### ISSUE TITLE
Supress DIFUnpacker

### ISSUE THREAD

**Issue by flagarde** [SDHCAL/streamout#2]
Hi,
DIFUnpacker just add a level of indirection for nothing for what i can see... It should be cleaner to supress it and put the members directly in the class that use it

**Comment by ggrenier** [comment]
You did it in pull request number 2. 
I agree to your comment.
The DIFUnpacker stuff was directly copied from Laurent's DAQ software. You already changed it in details so we can remove it.
This will make life slightly more complicated in case of changes to the decoding the DIF data.
