### ISSUE TITLE
Issue when compiling version as of July 12, 2022

### ISSUE THREAD

**Issue by ggrenier** [SDHCAL/streamout#36]
Usual setup on ubuntu : 
source /data/software/binaries/root/6.22.06/bin/thisroot.sh 
mkdir build; cd build
cmake ..
make

Output of make in following file : 
[out.txt](https://github.com/SDHCAL/streamout/files/9091435/out.txt)

**Comment by flagarde** [comment]
Does it solved the problem ?
I don't try to make it work with lower standard but 2017 is available in the gcc you gave me as reference 9.3~9.4 so I used it globally
